language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install scons; fi

script:
  - scons -C deps
  - mkdir build
  - cd build
  - cmake .. && make && ./wtest_suite --durations yes --warn NoAssertions
