language: cpp
compiler:
  - clang
  - gcc
os:
  - osx
#  - linux

osx_image: xcode7.3

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install scons; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$CC" == "gcc" ]]; then brew install gcc && export CC=gcc-6 && export CXX=g++-6; fi
  - $CXX -v

script:
  - scons -C deps
  - mkdir build
  - cd build
  - cmake .. && make && ./wtest_suite --durations yes --warn NoAssertions
